# Emit YARV instruction facts as an RPython-loadable module.
#
# Reads tool/ruby_vm/models (CRuby's own instruction metadata loader) and
# writes rpyyarv/yarv_insns.py. Reading only
#
# This emits FACTS derived from insns.def and never DECISIONS about
# which instructions RPyYARV implements or how they are numbered.
#
#   ruby generate.rb [-o OUTPUT]

require 'optparse'
require 'pathname'

TOP = Pathname.new(__dir__).parent.expand_path
$LOAD_PATH.unshift((TOP + 'tool').to_s)
require 'ruby_vm/models/instructions'

DEFAULT_OUT = TOP + 'rpyyarv' + 'yarv_insns.py'

def ruby_version
  src = (TOP + 'include/ruby/version.h').read
  %w[MAJOR MINOR TEENY].map { |k|
    src[/define RUBY_API_VERSION_#{k}\s+(\d+)/, 1]
  }.join('.')
end

def source_revision
  rev = `git -C #{TOP} rev-parse --short HEAD 2>/dev/null`.strip
  rev.empty? ? 'unknown' : rev
end

# insns.def writes variadic stack effects as "..."; @sig keeps the raw form
# while #pops drops it, so ask @sig.
def variadic?(insn)
  sig = insn.instance_variable_get(:@sig)
  sig[:pop].include?('...') || sig[:ret].include?('...')
end

def bare_instructions
  RubyVM::Instructions.select { |i| i.class.name =~ /BareInstruction/ }
end

def unified_instructions
  RubyVM::Instructions.select { |i| i.class.name =~ /OperandsUnification/ }
end

# "INT2FIX(0)" -> 0 ; "0" -> 0 ; anything else stays a string for the reader
# to reject loudly.
def decode_spec_value(text)
  case text
  when /\AINT2FIX\((-?\d+)\)\z/ then $1.to_i
  when /\A-?\d+\z/              then text.to_i
  else                               text
  end
end

def py_str(s)
  "'" + s.to_s.gsub('\\', '\\\\\\\\').gsub("'", "\\\\'") + "'"
end

def py_tuple(items)
  return '()' if items.empty?
  return "(#{items[0]},)" if items.size == 1
  "(#{items.join(', ')})"
end

def render
  bare = bare_instructions.sort_by(&:name)
  unif = unified_instructions.sort_by(&:name)
  out = []

  out << <<~HEADER
    # GENERATED BY rpyvmgen -- DO NOT EDIT.
    #
    # YARV instruction facts derived from insns.def.
    # Regenerate with:  make -C rpyvmgen
    #
    # Facts only. Which instructions RPyYARV implements, and how they map to
    # internal opcodes, is a design decision and lives in yarv_map.py.

    RUBY_API_VERSION = #{py_str(ruby_version)}
    SOURCE_REVISION = #{py_str(source_revision)}
    INSTRUCTION_COUNT = #{bare.size}
  HEADER

  # --- operand types -------------------------------------------------
  out << "\n# Instruction name -> tuple of operand type names, in order.\n"
  out << "# Drives operand transformation in the loader: dispatch on the type\n"
  out << "# rather than hard-coding per instruction.\n"
  out << "OPERANDS = {\n"
  (bare + unif).sort_by(&:name).each do |i|
    types = i.operands.map { |o| py_str(o[:type]) }
    out << "    #{py_str(i.name)}: #{py_tuple(types)},\n"
  end
  out << "}\n"

  # --- stack effects -------------------------------------------------
  out << "\n# Instruction name -> (pops, pushes). Absent when variadic:\n"
  out << "# insns.def writes those as '...' and computes sp_inc at run time.\n"
  out << "STACK = {\n"
  bare.each do |i|
    next if variadic?(i)
    out << "    #{py_str(i.name)}: (#{i.pops.size}, #{i.rets.size}),\n"
  end
  out << "}\n"

  variadic = bare.select { |i| variadic?(i) }.map(&:name)
  out << "\n# Stack effect is not static for these; consult sp_inc.\n"
  out << "VARIADIC = frozenset([\n"
  variadic.each { |n| out << "    #{py_str(n)},\n" }
  out << "])\n"

  # --- branches ------------------------------------------------------
  branch = (bare + unif).select { |i|
    i.operands.any? { |o| o[:type] == 'OFFSET' }
  }.map(&:name).sort
  out << "\n# Instructions carrying an OFFSET operand. This is the mechanical\n"
  out << "# test for 'is a branch', and later drives can_enter_jit placement.\n"
  out << "BRANCH = frozenset([\n"
  branch.each { |n| out << "    #{py_str(n)},\n" }
  out << "])\n"

  # --- leaf ----------------------------------------------------------
  # 'leaf' is always generated, with a default of !handles_sp. The value is a
  # C expression: literal true/false for most, a call for the few whose
  # leafness depends on an operand at run time.
  leaf, leaf_dynamic = [], []
  bare.each do |i|
    expr = i.instance_variable_get(:@attrs)['leaf'].expr.expr.strip.chomp(';')
    case expr
    when 'true'  then leaf << i.name
    when 'false' then next
    else              leaf_dynamic << i.name
    end
  end
  out << "\n# Leaf instructions push no new frame, so control cannot leave the\n"
  out << "# current ISeq while they run.\n"
  out << "LEAF = frozenset([\n"
  leaf.sort.each { |n| out << "    #{py_str(n)},\n" }
  out << "])\n"
  out << "\n# Leafness depends on an operand value, decided at run time.\n"
  out << "LEAF_DYNAMIC = frozenset([\n"
  leaf_dynamic.sort.each { |n| out << "    #{py_str(n)},\n" }
  out << "])\n"

  # --- specialization ------------------------------------------------
  out << "\n# Specialized variants generated from defs/opt_operand.def. These\n"
  out << "# appear in to_a but not in insns.def, so the loader must normalize\n"
  out << "# them back to the base instruction.\n"
  out << "#\n"
  out << "#   name -> (base_name, ((operand_name, fixed_value), ...))\n"
  out << "#\n"
  out << "# Operands not listed keep their position, in order.\n"
  out << "SPECIALIZED = {\n"
  unif.each do |i|
    fixed = i.spec.reject { |(_, v)| v == '*' }.map { |(decl, v)|
      "(#{py_str(decl[:name])}, #{decode_spec_value(v).inspect})"
    }
    out << "    #{py_str(i.name)}: (#{py_str(i.original.name)}, #{py_tuple(fixed)}),\n"
  end
  out << "}\n"

  # --- trace variants ------------------------------------------------
  out << "\n# TracePoint-enabled builds substitute these. RPyYARV does not\n"
  out << "# support TracePoint, so the loader must reject them explicitly.\n"
  out << "TRACE_PREFIX = 'trace_'\n"

  out.join
end

options = { out: DEFAULT_OUT }
OptionParser.new do |o|
  o.on('-o PATH', '--output=PATH') { |v| options[:out] = Pathname.new(v) }
  o.on('--stdout') { options[:out] = nil }
end.parse!(ARGV)

text = render
if options[:out]
  options[:out].write(text)
  warn "wrote #{options[:out].relative_path_from(TOP)} " \
       "(#{bare_instructions.size} instructions, ruby #{ruby_version})"
else
  print text
end
