# Emit YARV instruction facts as an RPython-loadable module.
#
# Reads tool/ruby_vm/models (CRuby's own instruction metadata loader) and
# writes rpyyarv/insns.py. Reading only
#
# This emits FACTS derived from insns.def and never DECISIONS about
# which instructions RPyYARV implements or how it encodes them.
#
# Opcode is the index into insns.def, and every table is a flat list indexed
# by it. Containers hold one RPython type each, or the annotator cannot type
# the prebuilt constants.
#
#   ruby generate.rb [-o OUTPUT]

require 'optparse'
require 'pathname'

TOP = Pathname.new(__dir__).parent.expand_path
$LOAD_PATH.unshift((TOP + 'tool').to_s)
require 'ruby_vm/models/instructions'

DEFAULT_OUT = TOP + 'rpyyarv' + 'insns.py'

# An instruction whose upcased name hit one of these would shadow it.
RESERVED = %w[
  RUBY_API_VERSION SOURCE_REVISION INSTRUCTION_COUNT
  NAMES NAME_TO_OP OPERAND_TYPES TYPE_NAMES
  STACK_POP STACK_PUSH IS_BRANCH IS_LEAF IS_LEAF_DYNAMIC
  SPEC_BASE SPEC_FILL TRACE_PREFIX
].freeze

def ruby_version
  src = (TOP + 'include/ruby/version.h').read
  %w[MAJOR MINOR TEENY].map { |k|
    src[/define RUBY_API_VERSION_#{k}\s+(\d+)/, 1]
  }.join('.')
end

def source_revision
  rev = `git -C #{TOP} rev-parse --short HEAD 2>/dev/null`.strip
  rev.empty? ? 'unknown' : rev
end

# insns.def writes variadic stack effects as "..."; @sig keeps the raw form
# while #pops drops it, so ask @sig.
def variadic?(insn)
  sig = insn.instance_variable_get(:@sig)
  sig[:pop].include?('...') || sig[:ret].include?('...')
end

# 'leaf' is always generated with a default of !handles_sp, and its value is a
# C expression, so classify by evaluating the text.
def leafness(insn)
  expr = insn.instance_variable_get(:@attrs)['leaf'].expr.expr.strip.chomp(';')
  case expr
  when 'true'  then :always
  when 'false' then :never
  else              :dynamic
  end
end

def bare_instructions
  RubyVM::Instructions.select { |i| i.class.name =~ /BareInstruction/ }
end

def unified_instructions
  RubyVM::Instructions.select { |i| i.class.name =~ /OperandsUnification/ }
end

# Refuse anything not representable as a plain operand word.
def decode_spec_value(insn, operand, text)
  case text
  when /\AINT2FIX\((-?\d+)\)\z/ then $1.to_i
  when /\A-?\d+\z/              then text.to_i
  else
    abort "generate: #{insn}.#{operand} specialized to non-integer #{text.inspect}"
  end
end

def py_str(s)
  "'" + s.to_s.gsub('\\', '\\\\\\\\').gsub("'", "\\\\'") + "'"
end

def render
  bare = bare_instructions
  unif = unified_instructions
  op_of = {}
  bare.each_with_index { |i, n| op_of[i.name] = n }

  types = bare.flat_map { |i| i.operands.map { |o| o[:type] } }.uniq.sort
  type_code = {}
  types.each_with_index { |t, n| type_code[t] = n }

  bare.each do |i|
    if RESERVED.include?(i.name.upcase)
      abort "generate: instruction #{i.name} collides with a table name"
    end
  end

  out = []
  out << <<~HEADER
    # GENERATED BY rpyvmgen -- DO NOT EDIT.
    #
    # YARV instruction facts derived from insns.def.
    # Regenerate with:  make -C rpyvmgen
    #
    # Opcode numbering is insns.def order, so it covers every instruction
    # whether or not RPyYARV implements it. Which ones it implements, and how
    # their operands are encoded, lives in yarv_map.py; optable.py joins the
    # two. Every table here is indexed by opcode.

    RUBY_API_VERSION = #{py_str(ruby_version)}
    SOURCE_REVISION = #{py_str(source_revision)}
    INSTRUCTION_COUNT = #{bare.size}
  HEADER

  out << "\n"
  bare.each_with_index { |i, n| out << "#{i.name.upcase} = #{n}\n" }

  out << "\nNAMES = [\n"
  bare.each { |i| out << "    #{py_str(i.name)},\n" }
  out << "]\n"

  out << "\n# Loader entry point, after normalizing specialized variants\n"
  out << "# through SPEC_BASE.\n"
  out << "NAME_TO_OP = {\n"
  bare.each_with_index { |i, n| out << "    #{py_str(i.name)}: #{n},\n" }
  out << "}\n"

  out << "\n# Operand transformation dispatches on these codes, not on names.\n"
  types.each { |t| out << "T_#{t.upcase} = #{type_code[t]}\n" }
  out << "\nTYPE_NAMES = [\n"
  types.each { |t| out << "    #{py_str(t)},\n" }
  out << "]\n"

  out << "\nOPERAND_TYPES = [\n"
  bare.each do |i|
    codes = i.operands.map { |o| type_code[o[:type]] }
    out << "    [#{codes.join(', ')}],  # #{i.name}\n"
  end
  out << "]\n"

  out << "\n# Static stack effect; -1 where insns.def writes '...' and the\n"
  out << "# effect is computed by sp_inc at run time.\n"
  %w[pop push].each do |which|
    out << "STACK_#{which.upcase} = [\n"
    bare.each do |i|
      n = variadic?(i) ? -1 : (which == 'pop' ? i.pops.size : i.rets.size)
      out << "    #{n},  # #{i.name}\n"
    end
    out << "]\n"
  end

  out << "\n# Carries an OFFSET operand: the mechanical test for 'is a branch',\n"
  out << "# and later the placement rule for can_enter_jit.\n"
  out << "IS_BRANCH = [\n"
  bare.each do |i|
    b = i.operands.any? { |o| o[:type] == 'OFFSET' }
    out << "    #{b ? 'True' : 'False'},  # #{i.name}\n"
  end
  out << "]\n"

  out << "\n# Leaf instructions push no new frame, so control cannot leave the\n"
  out << "# current ISeq while they run.\n"
  out << "IS_LEAF = [\n"
  bare.each { |i| out << "    #{leafness(i) == :always ? 'True' : 'False'},  # #{i.name}\n" }
  out << "]\n"
  out << "\n# Leafness depends on an operand value, decided at run time.\n"
  out << "IS_LEAF_DYNAMIC = [\n"
  bare.each { |i| out << "    #{leafness(i) == :dynamic ? 'True' : 'False'},  # #{i.name}\n" }
  out << "]\n"

  out << "\n# Variants from defs/opt_operand.def. They appear in to_a but not in\n"
  out << "# insns.def, so the loader takes the base opcode from SPEC_BASE and\n"
  out << "# splices the fixed (position, value) pairs back into the operands.\n"
  out << "SPEC_BASE = {\n"
  unif.each do |i|
    out << "    #{py_str(i.name)}: #{op_of.fetch(i.original.name)},  # #{i.original.name}\n"
  end
  out << "}\n"
  out << "\nSPEC_FILL = {\n"
  unif.each do |i|
    fixed = i.spec.each_with_index.reject { |(_, v), _| v == '*' }.map { |(decl, v), pos|
      "(#{pos}, #{decode_spec_value(i.name, decl[:name], v)})"
    }
    out << "    #{py_str(i.name)}: [#{fixed.join(', ')}],\n"
  end
  out << "}\n"

  out << "\n# TracePoint-enabled builds substitute these. RPyYARV does not\n"
  out << "# support TracePoint, so the loader must reject them explicitly.\n"
  out << "TRACE_PREFIX = 'trace_'\n"

  out.join
end

options = { out: DEFAULT_OUT }
OptionParser.new do |o|
  o.on('-o PATH', '--output=PATH') { |v| options[:out] = Pathname.new(v) }
  o.on('--stdout') { options[:out] = nil }
end.parse!(ARGV)

text = render
if options[:out]
  options[:out].write(text)
  warn "wrote #{options[:out].relative_path_from(TOP)} " \
       "(#{bare_instructions.size} instructions, ruby #{ruby_version})"
else
  print text
end
