# GENERATED BY rpyvmgen -- DO NOT EDIT (regenerate: make -C rpyvmgen); opcode order follows insns.def and every table here is indexed by opcode.

RUBY_API_VERSION = '4.0.0'
SOURCE_REVISION = '3c77b83724'
INSTRUCTION_COUNT = 103

NOP = 0
GETLOCAL = 1
SETLOCAL = 2
GETBLOCKPARAM = 3
SETBLOCKPARAM = 4
GETBLOCKPARAMPROXY = 5
GETSPECIAL = 6
SETSPECIAL = 7
GETINSTANCEVARIABLE = 8
SETINSTANCEVARIABLE = 9
GETCLASSVARIABLE = 10
SETCLASSVARIABLE = 11
OPT_GETCONSTANT_PATH = 12
GETCONSTANT = 13
SETCONSTANT = 14
GETGLOBAL = 15
SETGLOBAL = 16
PUTNIL = 17
PUTSELF = 18
PUTOBJECT = 19
PUTSPECIALOBJECT = 20
PUTSTRING = 21
PUTCHILLEDSTRING = 22
CONCATSTRINGS = 23
ANYTOSTRING = 24
TOREGEXP = 25
INTERN = 26
NEWARRAY = 27
PUSHTOARRAYKWSPLAT = 28
DUPARRAY = 29
DUPHASH = 30
EXPANDARRAY = 31
CONCATARRAY = 32
CONCATTOARRAY = 33
PUSHTOARRAY = 34
SPLATARRAY = 35
SPLATKW = 36
NEWHASH = 37
NEWRANGE = 38
POP = 39
DUP = 40
DUPN = 41
SWAP = 42
OPT_REVERSE = 43
TOPN = 44
SETN = 45
ADJUSTSTACK = 46
DEFINED = 47
DEFINEDIVAR = 48
CHECKMATCH = 49
CHECKKEYWORD = 50
CHECKTYPE = 51
DEFINECLASS = 52
DEFINEMETHOD = 53
DEFINESMETHOD = 54
SEND = 55
SENDFORWARD = 56
OPT_SEND_WITHOUT_BLOCK = 57
OPT_NEW = 58
OBJTOSTRING = 59
OPT_ARY_FREEZE = 60
OPT_HASH_FREEZE = 61
OPT_STR_FREEZE = 62
OPT_NIL_P = 63
OPT_STR_UMINUS = 64
OPT_DUPARRAY_SEND = 65
OPT_NEWARRAY_SEND = 66
INVOKESUPER = 67
INVOKESUPERFORWARD = 68
INVOKEBLOCK = 69
LEAVE = 70
THROW = 71
JUMP = 72
BRANCHIF = 73
BRANCHUNLESS = 74
BRANCHNIL = 75
ONCE = 76
OPT_CASE_DISPATCH = 77
OPT_PLUS = 78
OPT_MINUS = 79
OPT_MULT = 80
OPT_DIV = 81
OPT_MOD = 82
OPT_EQ = 83
OPT_NEQ = 84
OPT_LT = 85
OPT_LE = 86
OPT_GT = 87
OPT_GE = 88
OPT_LTLT = 89
OPT_AND = 90
OPT_OR = 91
OPT_AREF = 92
OPT_ASET = 93
OPT_LENGTH = 94
OPT_SIZE = 95
OPT_EMPTY_P = 96
OPT_SUCC = 97
OPT_NOT = 98
OPT_REGEXPMATCH2 = 99
INVOKEBUILTIN = 100
OPT_INVOKEBUILTIN_DELEGATE = 101
OPT_INVOKEBUILTIN_DELEGATE_LEAVE = 102

NAMES = [
    'nop',
    'getlocal',
    'setlocal',
    'getblockparam',
    'setblockparam',
    'getblockparamproxy',
    'getspecial',
    'setspecial',
    'getinstancevariable',
    'setinstancevariable',
    'getclassvariable',
    'setclassvariable',
    'opt_getconstant_path',
    'getconstant',
    'setconstant',
    'getglobal',
    'setglobal',
    'putnil',
    'putself',
    'putobject',
    'putspecialobject',
    'putstring',
    'putchilledstring',
    'concatstrings',
    'anytostring',
    'toregexp',
    'intern',
    'newarray',
    'pushtoarraykwsplat',
    'duparray',
    'duphash',
    'expandarray',
    'concatarray',
    'concattoarray',
    'pushtoarray',
    'splatarray',
    'splatkw',
    'newhash',
    'newrange',
    'pop',
    'dup',
    'dupn',
    'swap',
    'opt_reverse',
    'topn',
    'setn',
    'adjuststack',
    'defined',
    'definedivar',
    'checkmatch',
    'checkkeyword',
    'checktype',
    'defineclass',
    'definemethod',
    'definesmethod',
    'send',
    'sendforward',
    'opt_send_without_block',
    'opt_new',
    'objtostring',
    'opt_ary_freeze',
    'opt_hash_freeze',
    'opt_str_freeze',
    'opt_nil_p',
    'opt_str_uminus',
    'opt_duparray_send',
    'opt_newarray_send',
    'invokesuper',
    'invokesuperforward',
    'invokeblock',
    'leave',
    'throw',
    'jump',
    'branchif',
    'branchunless',
    'branchnil',
    'once',
    'opt_case_dispatch',
    'opt_plus',
    'opt_minus',
    'opt_mult',
    'opt_div',
    'opt_mod',
    'opt_eq',
    'opt_neq',
    'opt_lt',
    'opt_le',
    'opt_gt',
    'opt_ge',
    'opt_ltlt',
    'opt_and',
    'opt_or',
    'opt_aref',
    'opt_aset',
    'opt_length',
    'opt_size',
    'opt_empty_p',
    'opt_succ',
    'opt_not',
    'opt_regexpmatch2',
    'invokebuiltin',
    'opt_invokebuiltin_delegate',
    'opt_invokebuiltin_delegate_leave',
]

# Loader entry point, after normalizing specialized variants through SPEC_BASE.
NAME_TO_OP = {
    'nop': 0,
    'getlocal': 1,
    'setlocal': 2,
    'getblockparam': 3,
    'setblockparam': 4,
    'getblockparamproxy': 5,
    'getspecial': 6,
    'setspecial': 7,
    'getinstancevariable': 8,
    'setinstancevariable': 9,
    'getclassvariable': 10,
    'setclassvariable': 11,
    'opt_getconstant_path': 12,
    'getconstant': 13,
    'setconstant': 14,
    'getglobal': 15,
    'setglobal': 16,
    'putnil': 17,
    'putself': 18,
    'putobject': 19,
    'putspecialobject': 20,
    'putstring': 21,
    'putchilledstring': 22,
    'concatstrings': 23,
    'anytostring': 24,
    'toregexp': 25,
    'intern': 26,
    'newarray': 27,
    'pushtoarraykwsplat': 28,
    'duparray': 29,
    'duphash': 30,
    'expandarray': 31,
    'concatarray': 32,
    'concattoarray': 33,
    'pushtoarray': 34,
    'splatarray': 35,
    'splatkw': 36,
    'newhash': 37,
    'newrange': 38,
    'pop': 39,
    'dup': 40,
    'dupn': 41,
    'swap': 42,
    'opt_reverse': 43,
    'topn': 44,
    'setn': 45,
    'adjuststack': 46,
    'defined': 47,
    'definedivar': 48,
    'checkmatch': 49,
    'checkkeyword': 50,
    'checktype': 51,
    'defineclass': 52,
    'definemethod': 53,
    'definesmethod': 54,
    'send': 55,
    'sendforward': 56,
    'opt_send_without_block': 57,
    'opt_new': 58,
    'objtostring': 59,
    'opt_ary_freeze': 60,
    'opt_hash_freeze': 61,
    'opt_str_freeze': 62,
    'opt_nil_p': 63,
    'opt_str_uminus': 64,
    'opt_duparray_send': 65,
    'opt_newarray_send': 66,
    'invokesuper': 67,
    'invokesuperforward': 68,
    'invokeblock': 69,
    'leave': 70,
    'throw': 71,
    'jump': 72,
    'branchif': 73,
    'branchunless': 74,
    'branchnil': 75,
    'once': 76,
    'opt_case_dispatch': 77,
    'opt_plus': 78,
    'opt_minus': 79,
    'opt_mult': 80,
    'opt_div': 81,
    'opt_mod': 82,
    'opt_eq': 83,
    'opt_neq': 84,
    'opt_lt': 85,
    'opt_le': 86,
    'opt_gt': 87,
    'opt_ge': 88,
    'opt_ltlt': 89,
    'opt_and': 90,
    'opt_or': 91,
    'opt_aref': 92,
    'opt_aset': 93,
    'opt_length': 94,
    'opt_size': 95,
    'opt_empty_p': 96,
    'opt_succ': 97,
    'opt_not': 98,
    'opt_regexpmatch2': 99,
    'invokebuiltin': 100,
    'opt_invokebuiltin_delegate': 101,
    'opt_invokebuiltin_delegate_leave': 102,
}

# Operand transformation dispatches on these codes, not on names.
T_CALL_DATA = 0
T_CDHASH = 1
T_IC = 2
T_ICVARC = 3
T_ID = 4
T_ISE = 5
T_ISEQ = 6
T_IVC = 7
T_OFFSET = 8
T_RB_BUILTIN = 9
T_VALUE = 10
T_LINDEX_T = 11
T_RB_NUM_T = 12

TYPE_NAMES = [
    'CALL_DATA',
    'CDHASH',
    'IC',
    'ICVARC',
    'ID',
    'ISE',
    'ISEQ',
    'IVC',
    'OFFSET',
    'RB_BUILTIN',
    'VALUE',
    'lindex_t',
    'rb_num_t',
]

OPERAND_TYPES = [
    [],  # nop
    [11, 12],  # getlocal
    [11, 12],  # setlocal
    [11, 12],  # getblockparam
    [11, 12],  # setblockparam
    [11, 12],  # getblockparamproxy
    [12, 12],  # getspecial
    [12],  # setspecial
    [4, 7],  # getinstancevariable
    [4, 7],  # setinstancevariable
    [4, 3],  # getclassvariable
    [4, 3],  # setclassvariable
    [2],  # opt_getconstant_path
    [4],  # getconstant
    [4],  # setconstant
    [4],  # getglobal
    [4],  # setglobal
    [],  # putnil
    [],  # putself
    [10],  # putobject
    [12],  # putspecialobject
    [10],  # putstring
    [10],  # putchilledstring
    [12],  # concatstrings
    [],  # anytostring
    [12, 12],  # toregexp
    [],  # intern
    [12],  # newarray
    [],  # pushtoarraykwsplat
    [10],  # duparray
    [10],  # duphash
    [12, 12],  # expandarray
    [],  # concatarray
    [],  # concattoarray
    [12],  # pushtoarray
    [10],  # splatarray
    [],  # splatkw
    [12],  # newhash
    [12],  # newrange
    [],  # pop
    [],  # dup
    [12],  # dupn
    [],  # swap
    [12],  # opt_reverse
    [12],  # topn
    [12],  # setn
    [12],  # adjuststack
    [12, 10, 10],  # defined
    [4, 7, 10],  # definedivar
    [12],  # checkmatch
    [11, 11],  # checkkeyword
    [12],  # checktype
    [4, 6, 12],  # defineclass
    [4, 6],  # definemethod
    [4, 6],  # definesmethod
    [0, 6],  # send
    [0, 6],  # sendforward
    [0],  # opt_send_without_block
    [0, 8],  # opt_new
    [0],  # objtostring
    [10, 0],  # opt_ary_freeze
    [10, 0],  # opt_hash_freeze
    [10, 0],  # opt_str_freeze
    [0],  # opt_nil_p
    [10, 0],  # opt_str_uminus
    [10, 4, 12],  # opt_duparray_send
    [12, 12],  # opt_newarray_send
    [0, 6],  # invokesuper
    [0, 6],  # invokesuperforward
    [0],  # invokeblock
    [],  # leave
    [12],  # throw
    [8],  # jump
    [8],  # branchif
    [8],  # branchunless
    [8],  # branchnil
    [6, 5],  # once
    [1, 8],  # opt_case_dispatch
    [0],  # opt_plus
    [0],  # opt_minus
    [0],  # opt_mult
    [0],  # opt_div
    [0],  # opt_mod
    [0],  # opt_eq
    [0, 0],  # opt_neq
    [0],  # opt_lt
    [0],  # opt_le
    [0],  # opt_gt
    [0],  # opt_ge
    [0],  # opt_ltlt
    [0],  # opt_and
    [0],  # opt_or
    [0],  # opt_aref
    [0],  # opt_aset
    [0],  # opt_length
    [0],  # opt_size
    [0],  # opt_empty_p
    [0],  # opt_succ
    [0],  # opt_not
    [0],  # opt_regexpmatch2
    [9],  # invokebuiltin
    [9, 12],  # opt_invokebuiltin_delegate
    [9, 12],  # opt_invokebuiltin_delegate_leave
]

# Static stack effect; -1 where insns.def writes '...' and the effect is computed by sp_inc at run time.
STACK_POP = [
    0,  # nop
    0,  # getlocal
    1,  # setlocal
    0,  # getblockparam
    1,  # setblockparam
    0,  # getblockparamproxy
    0,  # getspecial
    1,  # setspecial
    0,  # getinstancevariable
    1,  # setinstancevariable
    0,  # getclassvariable
    1,  # setclassvariable
    0,  # opt_getconstant_path
    2,  # getconstant
    2,  # setconstant
    0,  # getglobal
    1,  # setglobal
    0,  # putnil
    0,  # putself
    0,  # putobject
    0,  # putspecialobject
    0,  # putstring
    0,  # putchilledstring
    -1,  # concatstrings
    2,  # anytostring
    -1,  # toregexp
    1,  # intern
    -1,  # newarray
    2,  # pushtoarraykwsplat
    0,  # duparray
    0,  # duphash
    -1,  # expandarray
    2,  # concatarray
    2,  # concattoarray
    -1,  # pushtoarray
    1,  # splatarray
    2,  # splatkw
    -1,  # newhash
    2,  # newrange
    1,  # pop
    1,  # dup
    -1,  # dupn
    2,  # swap
    -1,  # opt_reverse
    -1,  # topn
    -1,  # setn
    -1,  # adjuststack
    1,  # defined
    0,  # definedivar
    2,  # checkmatch
    0,  # checkkeyword
    1,  # checktype
    2,  # defineclass
    0,  # definemethod
    1,  # definesmethod
    -1,  # send
    -1,  # sendforward
    -1,  # opt_send_without_block
    0,  # opt_new
    1,  # objtostring
    0,  # opt_ary_freeze
    0,  # opt_hash_freeze
    0,  # opt_str_freeze
    1,  # opt_nil_p
    0,  # opt_str_uminus
    -1,  # opt_duparray_send
    -1,  # opt_newarray_send
    -1,  # invokesuper
    -1,  # invokesuperforward
    -1,  # invokeblock
    1,  # leave
    1,  # throw
    0,  # jump
    1,  # branchif
    1,  # branchunless
    1,  # branchnil
    0,  # once
    -1,  # opt_case_dispatch
    2,  # opt_plus
    2,  # opt_minus
    2,  # opt_mult
    2,  # opt_div
    2,  # opt_mod
    2,  # opt_eq
    2,  # opt_neq
    2,  # opt_lt
    2,  # opt_le
    2,  # opt_gt
    2,  # opt_ge
    2,  # opt_ltlt
    2,  # opt_and
    2,  # opt_or
    2,  # opt_aref
    3,  # opt_aset
    1,  # opt_length
    1,  # opt_size
    1,  # opt_empty_p
    1,  # opt_succ
    1,  # opt_not
    2,  # opt_regexpmatch2
    -1,  # invokebuiltin
    0,  # opt_invokebuiltin_delegate
    0,  # opt_invokebuiltin_delegate_leave
]
STACK_PUSH = [
    0,  # nop
    1,  # getlocal
    0,  # setlocal
    1,  # getblockparam
    0,  # setblockparam
    1,  # getblockparamproxy
    1,  # getspecial
    0,  # setspecial
    1,  # getinstancevariable
    0,  # setinstancevariable
    1,  # getclassvariable
    0,  # setclassvariable
    1,  # opt_getconstant_path
    1,  # getconstant
    0,  # setconstant
    1,  # getglobal
    0,  # setglobal
    1,  # putnil
    1,  # putself
    1,  # putobject
    1,  # putspecialobject
    1,  # putstring
    1,  # putchilledstring
    -1,  # concatstrings
    1,  # anytostring
    -1,  # toregexp
    1,  # intern
    -1,  # newarray
    1,  # pushtoarraykwsplat
    1,  # duparray
    1,  # duphash
    -1,  # expandarray
    1,  # concatarray
    1,  # concattoarray
    -1,  # pushtoarray
    1,  # splatarray
    2,  # splatkw
    -1,  # newhash
    1,  # newrange
    0,  # pop
    2,  # dup
    -1,  # dupn
    2,  # swap
    -1,  # opt_reverse
    -1,  # topn
    -1,  # setn
    -1,  # adjuststack
    1,  # defined
    1,  # definedivar
    1,  # checkmatch
    1,  # checkkeyword
    1,  # checktype
    1,  # defineclass
    0,  # definemethod
    0,  # definesmethod
    -1,  # send
    -1,  # sendforward
    -1,  # opt_send_without_block
    0,  # opt_new
    1,  # objtostring
    1,  # opt_ary_freeze
    1,  # opt_hash_freeze
    1,  # opt_str_freeze
    1,  # opt_nil_p
    1,  # opt_str_uminus
    -1,  # opt_duparray_send
    -1,  # opt_newarray_send
    -1,  # invokesuper
    -1,  # invokesuperforward
    -1,  # invokeblock
    1,  # leave
    1,  # throw
    0,  # jump
    0,  # branchif
    0,  # branchunless
    0,  # branchnil
    1,  # once
    -1,  # opt_case_dispatch
    1,  # opt_plus
    1,  # opt_minus
    1,  # opt_mult
    1,  # opt_div
    1,  # opt_mod
    1,  # opt_eq
    1,  # opt_neq
    1,  # opt_lt
    1,  # opt_le
    1,  # opt_gt
    1,  # opt_ge
    1,  # opt_ltlt
    1,  # opt_and
    1,  # opt_or
    1,  # opt_aref
    1,  # opt_aset
    1,  # opt_length
    1,  # opt_size
    1,  # opt_empty_p
    1,  # opt_succ
    1,  # opt_not
    1,  # opt_regexpmatch2
    -1,  # invokebuiltin
    1,  # opt_invokebuiltin_delegate
    1,  # opt_invokebuiltin_delegate_leave
]

# Carries an OFFSET operand: the mechanical test for 'is a branch', and later the placement rule for can_enter_jit.
IS_BRANCH = [
    False,  # nop
    False,  # getlocal
    False,  # setlocal
    False,  # getblockparam
    False,  # setblockparam
    False,  # getblockparamproxy
    False,  # getspecial
    False,  # setspecial
    False,  # getinstancevariable
    False,  # setinstancevariable
    False,  # getclassvariable
    False,  # setclassvariable
    False,  # opt_getconstant_path
    False,  # getconstant
    False,  # setconstant
    False,  # getglobal
    False,  # setglobal
    False,  # putnil
    False,  # putself
    False,  # putobject
    False,  # putspecialobject
    False,  # putstring
    False,  # putchilledstring
    False,  # concatstrings
    False,  # anytostring
    False,  # toregexp
    False,  # intern
    False,  # newarray
    False,  # pushtoarraykwsplat
    False,  # duparray
    False,  # duphash
    False,  # expandarray
    False,  # concatarray
    False,  # concattoarray
    False,  # pushtoarray
    False,  # splatarray
    False,  # splatkw
    False,  # newhash
    False,  # newrange
    False,  # pop
    False,  # dup
    False,  # dupn
    False,  # swap
    False,  # opt_reverse
    False,  # topn
    False,  # setn
    False,  # adjuststack
    False,  # defined
    False,  # definedivar
    False,  # checkmatch
    False,  # checkkeyword
    False,  # checktype
    False,  # defineclass
    False,  # definemethod
    False,  # definesmethod
    False,  # send
    False,  # sendforward
    False,  # opt_send_without_block
    True,  # opt_new
    False,  # objtostring
    False,  # opt_ary_freeze
    False,  # opt_hash_freeze
    False,  # opt_str_freeze
    False,  # opt_nil_p
    False,  # opt_str_uminus
    False,  # opt_duparray_send
    False,  # opt_newarray_send
    False,  # invokesuper
    False,  # invokesuperforward
    False,  # invokeblock
    False,  # leave
    False,  # throw
    True,  # jump
    True,  # branchif
    True,  # branchunless
    True,  # branchnil
    False,  # once
    True,  # opt_case_dispatch
    False,  # opt_plus
    False,  # opt_minus
    False,  # opt_mult
    False,  # opt_div
    False,  # opt_mod
    False,  # opt_eq
    False,  # opt_neq
    False,  # opt_lt
    False,  # opt_le
    False,  # opt_gt
    False,  # opt_ge
    False,  # opt_ltlt
    False,  # opt_and
    False,  # opt_or
    False,  # opt_aref
    False,  # opt_aset
    False,  # opt_length
    False,  # opt_size
    False,  # opt_empty_p
    False,  # opt_succ
    False,  # opt_not
    False,  # opt_regexpmatch2
    False,  # invokebuiltin
    False,  # opt_invokebuiltin_delegate
    False,  # opt_invokebuiltin_delegate_leave
]

# Leaf instructions push no new frame, so control cannot leave the current ISeq while they run.
IS_LEAF = [
    True,  # nop
    True,  # getlocal
    True,  # setlocal
    True,  # getblockparam
    True,  # setblockparam
    True,  # getblockparamproxy
    False,  # getspecial
    True,  # setspecial
    False,  # getinstancevariable
    False,  # setinstancevariable
    False,  # getclassvariable
    False,  # setclassvariable
    False,  # opt_getconstant_path
    False,  # getconstant
    False,  # setconstant
    False,  # getglobal
    False,  # setglobal
    True,  # putnil
    True,  # putself
    True,  # putobject
    False,  # putspecialobject
    True,  # putstring
    True,  # putchilledstring
    False,  # concatstrings
    True,  # anytostring
    False,  # toregexp
    True,  # intern
    True,  # newarray
    True,  # pushtoarraykwsplat
    True,  # duparray
    True,  # duphash
    False,  # expandarray
    False,  # concatarray
    False,  # concattoarray
    True,  # pushtoarray
    False,  # splatarray
    False,  # splatkw
    False,  # newhash
    False,  # newrange
    True,  # pop
    True,  # dup
    True,  # dupn
    True,  # swap
    True,  # opt_reverse
    True,  # topn
    True,  # setn
    True,  # adjuststack
    False,  # defined
    False,  # definedivar
    False,  # checkmatch
    True,  # checkkeyword
    True,  # checktype
    False,  # defineclass
    False,  # definemethod
    False,  # definesmethod
    False,  # send
    False,  # sendforward
    False,  # opt_send_without_block
    False,  # opt_new
    False,  # objtostring
    True,  # opt_ary_freeze
    True,  # opt_hash_freeze
    True,  # opt_str_freeze
    True,  # opt_nil_p
    True,  # opt_str_uminus
    False,  # opt_duparray_send
    False,  # opt_newarray_send
    False,  # invokesuper
    False,  # invokesuperforward
    False,  # invokeblock
    False,  # leave
    False,  # throw
    False,  # jump
    False,  # branchif
    False,  # branchunless
    False,  # branchnil
    False,  # once
    True,  # opt_case_dispatch
    True,  # opt_plus
    True,  # opt_minus
    True,  # opt_mult
    False,  # opt_div
    False,  # opt_mod
    True,  # opt_eq
    True,  # opt_neq
    True,  # opt_lt
    True,  # opt_le
    True,  # opt_gt
    True,  # opt_ge
    False,  # opt_ltlt
    True,  # opt_and
    True,  # opt_or
    False,  # opt_aref
    False,  # opt_aset
    True,  # opt_length
    True,  # opt_size
    True,  # opt_empty_p
    True,  # opt_succ
    True,  # opt_not
    False,  # opt_regexpmatch2
    False,  # invokebuiltin
    False,  # opt_invokebuiltin_delegate
    False,  # opt_invokebuiltin_delegate_leave
]

# Leafness depends on an operand value, decided at run time.
IS_LEAF_DYNAMIC = [
    False,  # nop
    False,  # getlocal
    False,  # setlocal
    False,  # getblockparam
    False,  # setblockparam
    False,  # getblockparamproxy
    True,  # getspecial
    False,  # setspecial
    False,  # getinstancevariable
    False,  # setinstancevariable
    False,  # getclassvariable
    False,  # setclassvariable
    False,  # opt_getconstant_path
    False,  # getconstant
    False,  # setconstant
    False,  # getglobal
    False,  # setglobal
    False,  # putnil
    False,  # putself
    False,  # putobject
    True,  # putspecialobject
    False,  # putstring
    False,  # putchilledstring
    False,  # concatstrings
    False,  # anytostring
    False,  # toregexp
    False,  # intern
    False,  # newarray
    False,  # pushtoarraykwsplat
    False,  # duparray
    False,  # duphash
    False,  # expandarray
    False,  # concatarray
    False,  # concattoarray
    False,  # pushtoarray
    False,  # splatarray
    False,  # splatkw
    False,  # newhash
    False,  # newrange
    False,  # pop
    False,  # dup
    False,  # dupn
    False,  # swap
    False,  # opt_reverse
    False,  # topn
    False,  # setn
    False,  # adjuststack
    True,  # defined
    False,  # definedivar
    True,  # checkmatch
    False,  # checkkeyword
    False,  # checktype
    False,  # defineclass
    False,  # definemethod
    False,  # definesmethod
    False,  # send
    False,  # sendforward
    True,  # opt_send_without_block
    False,  # opt_new
    False,  # objtostring
    False,  # opt_ary_freeze
    False,  # opt_hash_freeze
    False,  # opt_str_freeze
    False,  # opt_nil_p
    False,  # opt_str_uminus
    False,  # opt_duparray_send
    False,  # opt_newarray_send
    False,  # invokesuper
    False,  # invokesuperforward
    True,  # invokeblock
    False,  # leave
    False,  # throw
    False,  # jump
    False,  # branchif
    False,  # branchunless
    False,  # branchnil
    False,  # once
    False,  # opt_case_dispatch
    False,  # opt_plus
    False,  # opt_minus
    False,  # opt_mult
    False,  # opt_div
    False,  # opt_mod
    False,  # opt_eq
    False,  # opt_neq
    False,  # opt_lt
    False,  # opt_le
    False,  # opt_gt
    False,  # opt_ge
    False,  # opt_ltlt
    False,  # opt_and
    False,  # opt_or
    False,  # opt_aref
    False,  # opt_aset
    False,  # opt_length
    False,  # opt_size
    False,  # opt_empty_p
    False,  # opt_succ
    False,  # opt_not
    False,  # opt_regexpmatch2
    False,  # invokebuiltin
    False,  # opt_invokebuiltin_delegate
    False,  # opt_invokebuiltin_delegate_leave
]

# Variants from defs/opt_operand.def. They appear in to_a but not in insns.def, so the loader takes the base opcode from SPEC_BASE and splices the fixed (position, value) pairs back into the operands.
SPEC_BASE = {
    'getlocal_WC_0': 1,  # getlocal
    'getlocal_WC_1': 1,  # getlocal
    'setlocal_WC_0': 2,  # setlocal
    'setlocal_WC_1': 2,  # setlocal
    'putobject_INT2FIX_0_': 19,  # putobject
    'putobject_INT2FIX_1_': 19,  # putobject
}

SPEC_FILL = {
    'getlocal_WC_0': [(1, 0)],
    'getlocal_WC_1': [(1, 1)],
    'setlocal_WC_0': [(1, 0)],
    'setlocal_WC_1': [(1, 1)],
    'putobject_INT2FIX_0_': [(0, 0)],
    'putobject_INT2FIX_1_': [(0, 1)],
}

# TracePoint-enabled builds substitute these. RPyYARV does not support TracePoint, so the loader must reject them explicitly.
TRACE_PREFIX = 'trace_'
