/* Emit host/<version>/consts.py: each host constant RPyYARV compiles in,
   read from the host's own headers so a port never re-types one.
   Built and run by `make host`; the boot checks re-read the same macros
   from the linked libruby, so a stale description fails loudly. */
#include <stdio.h>
#include <stddef.h>
#include <ruby.h>
#include <ruby/version.h>
#include "internal.h"
#include "shape.h"
#include "internal/array.h"
#include "internal/class.h"
#include "internal/imemo.h"
#include "internal/numeric.h"
#include "internal/struct.h"
#include "iseq.h"
#include "vm_core.h"
#include "vm_callinfo.h"
#include "compat.h"

#define C(name, expr) printf("%s = %ld\n", name, (long)(expr))
#define W(name, type, field) C(name, offsetof(type, field) / SIZEOF_VALUE)

int
main(void)
{
    printf("# GENERATED BY rpyyarv/host/hostconsts.c -- DO NOT EDIT "
           "(regenerate: make -C rpyyarv host)\n");
    printf("RUBY_API_VERSION = '%d.%d.%d'\n", RUBY_API_VERSION_MAJOR,
           RUBY_API_VERSION_MINOR, RUBY_API_VERSION_TEENY);

    /* special_consts.h */
    C("Q_FALSE", RUBY_Qfalse);
    C("Q_NIL", RUBY_Qnil);
    C("Q_TRUE", RUBY_Qtrue);
    C("Q_UNDEF", RUBY_Qundef);
    C("FIXNUM_FLAG", RUBY_FIXNUM_FLAG);
    C("IMMEDIATE_MASK", RUBY_IMMEDIATE_MASK);
    C("FLONUM_MASK", RUBY_FLONUM_MASK);
    C("FLONUM_FLAG", RUBY_FLONUM_FLAG);
    C("SYMBOL_MASK", ~(~0UL << RUBY_SPECIAL_SHIFT));
    C("SYMBOL_FLAG", RUBY_SYMBOL_FLAG);

    /* rbasic.h, value_type.h, fl_type.h */
    W("FLAGS_WORD", struct RBasic, flags);
    W("KLASS_WORD", struct RBasic, klass);
    C("T_MASK", RUBY_T_MASK);
    C("T_OBJECT", RUBY_T_OBJECT);
    C("T_CLASS", RUBY_T_CLASS);
    C("T_MODULE", RUBY_T_MODULE);
    C("T_ARRAY", RUBY_T_ARRAY);
    C("T_STRUCT", RUBY_T_STRUCT);
    C("T_DATA", RUBY_T_DATA);
    C("FL_FREEZE", RUBY_FL_FREEZE);
    C("FL_SINGLETON", RUBY_FL_SINGLETON);
    C("FL_SHAREABLE", RUBY_FL_SHAREABLE);
    C("FL_TYPED_DATA", RPYYARV_FL_TYPED_DATA);

    /* internal/numeric.h */
    W("FLOAT_VALUE_WORD", struct RFloat, float_value);

    /* shape.h, robject.h, internal/class.h */
    C("SHAPE_SHIFT", SHAPE_FLAG_SHIFT);
    C("SHAPE_ID_BITS", SHAPE_ID_NUM_BITS);
    C("SHAPE_ID_IN_FLAGS", RBASIC_SHAPE_ID_FIELD);
    C("IV_HEAP_MASK", RPYYARV_IV_HEAP_MASK);
    C("IV_HEAP_BITS", RPYYARV_IV_HEAP_BITS);
    C("IV_HEAP_BASE", RPYYARV_IV_HEAP_BASE);
    C("IV_HEAP_IS_OBJECT", RPYYARV_IV_HEAP_IS_OBJECT);
    W("FIELDS_WORD", struct RObject, as.ary);
    W("CLASS_FIELDS_WORD", struct RClass_and_rb_classext_t,
      classext.fields_obj);
    C("RCLASS_BOXABLE", RCLASS_BOXABLE);

    /* rarray.h, internal/array.h */
    C("ARY_EMBED_FLAG", RARRAY_EMBED_FLAG);
    C("ARY_EMBED_LEN_SHIFT", RARRAY_EMBED_LEN_SHIFT);
    C("ARY_EMBED_LEN_MASK", RARRAY_EMBED_LEN_MASK);
    W("ARY_HEAP_LEN_WORD", struct RArray, as.heap.len);
    W("ARY_HEAP_CAPA_WORD", struct RArray, as.heap.aux.capa);
    W("ARY_HEAP_PTR_WORD", struct RArray, as.heap.ptr);
    W("ARY_EMBED_WORD", struct RArray, as.ary);
    C("ARY_SHARED_FLAG", RARRAY_SHARED_FLAG);
    C("ARY_SHARED_ROOT_FLAG", RARRAY_SHARED_ROOT_FLAG);

    /* internal/struct.h */
    C("STRUCT_EMBED_LEN_SHIFT", RSTRUCT_EMBED_LEN_SHIFT);
    C("STRUCT_EMBED_LEN_MASK", RSTRUCT_EMBED_LEN_MASK);
    W("STRUCT_HEAP_LEN_WORD", struct RStruct, as.heap.len);
    W("STRUCT_HEAP_PTR_WORD", struct RStruct, as.heap.ptr);
    W("STRUCT_EMBED_WORD", struct RStruct, as.ary);

    /* vm_core.h */
    C("ENV_DATA_SIZE", VM_ENV_DATA_SIZE);
    C("KW_SPECIFIED_BITS_MAX", VM_KW_SPECIFIED_BITS_MAX);
    C("TAG_MASK", RUBY_TAG_MASK);
    C("TAG_NONE", RUBY_TAG_NONE);
    C("TAG_RETURN", RUBY_TAG_RETURN);
    C("TAG_BREAK", RUBY_TAG_BREAK);
    C("TAG_NEXT", RUBY_TAG_NEXT);
    C("TAG_RETRY", RUBY_TAG_RETRY);
    C("TAG_REDO", RUBY_TAG_REDO);
    C("DEFINECLASS_TYPE_MASK", VM_DEFINECLASS_TYPE_MASK);
    C("DEFINECLASS_TYPE_CLASS", VM_DEFINECLASS_TYPE_CLASS);
    C("DEFINECLASS_TYPE_SINGLETON_CLASS", VM_DEFINECLASS_TYPE_SINGLETON_CLASS);
    C("DEFINECLASS_TYPE_MODULE", VM_DEFINECLASS_TYPE_MODULE);
    C("DEFINECLASS_FLAG_SCOPED", VM_DEFINECLASS_FLAG_SCOPED);
    C("DEFINECLASS_FLAG_HAS_SUPERCLASS", VM_DEFINECLASS_FLAG_HAS_SUPERCLASS);
    C("SPECIAL_OBJECT_VMCORE", VM_SPECIAL_OBJECT_VMCORE);
    C("SPECIAL_OBJECT_CBASE", VM_SPECIAL_OBJECT_CBASE);
    C("SPECIAL_OBJECT_CONST_BASE", VM_SPECIAL_OBJECT_CONST_BASE);
    C("CHECKMATCH_TYPE_MASK", VM_CHECKMATCH_TYPE_MASK);
    C("CHECKMATCH_TYPE_WHEN", VM_CHECKMATCH_TYPE_WHEN);
    C("CHECKMATCH_TYPE_CASE", VM_CHECKMATCH_TYPE_CASE);
    C("CHECKMATCH_TYPE_RESCUE", VM_CHECKMATCH_TYPE_RESCUE);
    C("CHECKMATCH_ARRAY", VM_CHECKMATCH_ARRAY);
    C("NEWARRAY_SEND_MAX", VM_OPT_NEWARRAY_SEND_MAX);
    C("NEWARRAY_SEND_MIN", VM_OPT_NEWARRAY_SEND_MIN);
    C("NEWARRAY_SEND_HASH", VM_OPT_NEWARRAY_SEND_HASH);
    C("NEWARRAY_SEND_PACK", VM_OPT_NEWARRAY_SEND_PACK);
    C("NEWARRAY_SEND_PACK_BUFFER", VM_OPT_NEWARRAY_SEND_PACK_BUFFER);
    C("NEWARRAY_SEND_INCLUDE_P", VM_OPT_NEWARRAY_SEND_INCLUDE_P);

    /* vm_callinfo.h */
    C("CALL_FLAG_ARGS_SPLAT", VM_CALL_ARGS_SPLAT);
    C("CALL_FLAG_ARGS_BLOCKARG", VM_CALL_ARGS_BLOCKARG);
    C("CALL_FLAG_FCALL", VM_CALL_FCALL);
    C("CALL_FLAG_VCALL", VM_CALL_VCALL);
    C("CALL_FLAG_ARGS_SIMPLE", VM_CALL_ARGS_SIMPLE);
    C("CALL_FLAG_KWARG", VM_CALL_KWARG);
    C("CALL_FLAG_KW_SPLAT", VM_CALL_KW_SPLAT);
    C("CALL_FLAG_TAILCALL", VM_CALL_TAILCALL);
    C("CALL_FLAG_SUPER", VM_CALL_SUPER);
    C("CALL_FLAG_ZSUPER", VM_CALL_ZSUPER);
    C("CALL_FLAG_OPT_SEND", VM_CALL_OPT_SEND);
    C("CALL_FLAG_KW_SPLAT_MUT", VM_CALL_KW_SPLAT_MUT);
    C("CALL_FLAG_ARGS_SPLAT_MUT", VM_CALL_ARGS_SPLAT_MUT);
    C("CALL_FLAG_FORWARDING", VM_CALL_FORWARDING);

    /* iseq.h, enum defined_type */
    C("DEFINED_IVAR", DEFINED_IVAR);
    C("DEFINED_GVAR", DEFINED_GVAR);
    C("DEFINED_CVAR", DEFINED_CVAR);
    C("DEFINED_CONST", DEFINED_CONST);
    C("DEFINED_METHOD", DEFINED_METHOD);
    C("DEFINED_YIELD", DEFINED_YIELD);
    C("DEFINED_FUNC", DEFINED_FUNC);
    C("DEFINED_CONST_FROM", DEFINED_CONST_FROM);
    return 0;
}
